### ISSUE TITLE
ESPBoy AppStore support

### ISSUE THREAD

**Issue by felipemanga** [micojs/micojs.github.io#18]

**Comment by ESPboy-edu** [comment]
I can provide proprietary ESPboy OTA2 (AppStore) code over a secure channel to include it in the final bin when compiling :)
Keep in mind that you need about 40Kb of free RAM for the WiFi to work reliably.
I achieve this in the way that all buffers in RAM required for the main code are allocated to RAM only after the AppStore part of the code passes the entry check.

**Comment by ESPboy-edu** [comment]
DONE!
thanks!
